### PR TITLE
Add ability to not reject on cancel

### PR DESCRIPTION
**Pull request by szmarczak**

### CODE REVIEW

**Comment by sindresorhus** [comment]
What problem does this solve? Its use-case is unclear to me.

**Comment by szmarczak** [comment]
> What problem does this solve? Its use-case is unclear to me.

This solves the problem to resolve instead of reject on cancel. Real usage:

https://github.com/sindresorhus/p-event/blob/master/index.js#L42-L43

**Comment by szmarczak** [comment]
> You can just catch the rejection and check if it's a cancel event, like shown in the readme.

In depends on the usage. In this case it's not a good idea. I think

```js
const p = new PCancelable((resolve, reject, onCancel) => {
	onCancel(shouldReject => shouldReject(false));
	...
});
```

is more convenient than

```js
let shouldRejectOnCancel = true;
const p = PCancelable((resolve, reject, onCancel) => {
	shouldRejectOnCancel = false;
	...
}).catch(error => {
	if (err instanceof PCancelable.CancelError) {
		if (shouldRejectOnCancel) {
			throw error;
		}
	} else {
		throw error;
	}
});
```

**Comment by szmarczak** [comment]
New idea: if the cancel handler returns false, the cancel error won't be thrown. If it returns true, the cancel error will be thrown. If it's not a bool, assume it's `true`. Example:

```js
onCancel(() => false); // won't throw
onCancel(() => true); // will throw
onCancel(() => undefined); // will throw
onCancel(() => null); // will throw
```

**Comment by sindresorhus** [comment]
I'm still not sold on this. The above could also easily cause weird behavior if you accidentally return a value. I just don't think it's worth it to save a few lines for an edge-case use-case.

Your example could also be simplified:

```js
let shouldRejectOnCancel = true;
const p = PCancelable((resolve, reject, onCancel) => {
	shouldRejectOnCancel = false;
	...
}).catch(error => {
	if (!error.isCanceled || shouldRejectOnCancel) {
		throw error;
	}
});
```

I'm happy to consider other options.

**Comment by szmarczak** [comment]
So what about:
```js
const p = new PCancelable((resolve, reject, onCancel) => {
	onCancel(shouldReject => shouldReject(false));
	...
});
```

**Comment by sindresorhus** [comment]
I would rather have something like this if we're doing it:

```js
const p = new PCancelable((resolve, reject, onCancel) => {
	onCancel.shouldReject = false;
	onCancel(() => {

	});
	...
});
```

**Comment by szmarczak** [comment]
Two heads are better than one :)

**Comment by karpikpl** [comment]
hey,
Is this correct way of using this with `fn`?

```js
	const fn = PCancelable.fn(async (input, onCancel) => {

                onCancel.shouldReject = false;
		onCancel(() => {
			expect('this should be called').toBeTruthy();
		});

		await delay(50);

		return input;
	});

	const p = fn();

	p.cancel();
```

I coudln't find an example with `shouldReject` for the `fn` scenario

**Pull request merged**
