### PR TITLE
Ability to cancel by calling `onCancel(reason)`

### PR DESCRIPTION
**Pull request by szmarczak**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Not sure if this is a good idea, it would mean you could accidentally cancel the promise by not passing a handler to `onCancel();`. That could happen with logic like `onCancel(shouldHandleCancel ? () => {} : null);`.

You can solve this already by doing:

```js
const p = new PCancelable((resolve, reject, onCancel) => {
	p.cancel();
});
```

So what is your use-case for this?

**Comment by szmarczak** [comment]
> So what is your use-case for this?

**Comment by szmarczak** [comment]
Sorry, just accidentally clicked on the `Close and comment` button :P

**Comment by szmarczak** [comment]
> That could happen with logic like onCancel(shouldHandleCancel ? () => {} : null);.

I'd prefer `shouldHandleCancel && onCancel(() => {});` But

```js
if (shouldHandleCancel) {
	onCancel(() => {});
}
```

is more readable :)

> I'm all about creating readable code. You write code once, but it's read many many times.

**Comment by szmarczak** [comment]
I'm gonna close this. We can reopen when it's needed :)

**Comment by sindresorhus** [comment]
I'm still curious why you need to cancel the promise from inside the constructor. Can you elaborate? Maybe there's a better way to solve that.

**Comment by szmarczak** [comment]
> I'm still curious why you need to cancel the promise from inside the constructor. Can you elaborate? Maybe there's a better way to solve that.

Example: https://github.com/sindresorhus/p-event/blob/master/index.js#L42

I don't like

```js
const p = new PCancelable((resolve, reject, onCancel) => {
	...
		p.cancel(); // need to refer itself
	...
})
```

but I can accept it. It's not a big thing :)

**Comment by sindresorhus** [comment]
> Example: sindresorhus/p-event:index.js@master#L42

That is not using `p-cancelable` and it's not actually canceling the promise. (?)

**Comment by szmarczak** [comment]
> That is not using p-cancelable and it's not actually canceling the promise. (?)

Yeah, but I'm planning to. Is it a good idea?

**Comment by sindresorhus** [comment]
It might be better to go with `AbortSignal`. I don't really like it, but it seems that's what we're ending up with, so makes sense for consistency with the native platform. See: https://github.com/sindresorhus/delay/pull/35

**Pull request closed without merging**
